# Loading Numpy

In [1]:
import numpy as np

# The Basics

In [2]:
# Creating arrays
a = np.array([1,2,3])
a

array([1, 2, 3])

In [3]:
# 2d arrays
b = np.array([[1,2,3], [4,5,6]])
b

array([[1, 2, 3],
       [4, 5, 6]])

In [4]:
# Dimension of array
a.ndim

1

In [5]:
b.ndim

2

In [6]:
# Get shape
a.shape

(3,)

In [7]:
b.shape

(2, 3)

In [8]:
# Get type
a.dtype

dtype('int64')

In [9]:
c = np.array([6,7,8], dtype=np.float16)
c

array([6., 7., 8.], dtype=float16)

In [10]:
# get item size
a.itemsize

8

In [11]:
c.itemsize

2

In [12]:
# Get total size
a.size

3

In [13]:
c.size

3

# Accessing/Changing specific elements, rows, columns etc

In [14]:
a = np.array([[1,2,3,4,5,6,7], [8,9,10,11,12,13,14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [15]:
a.shape

(2, 7)

In [16]:
# get a specific element [r,c]
a[1, 5]

13

In [17]:
# Get a specific row
a[0, :]

array([1, 2, 3, 4, 5, 6, 7])

In [18]:
# Get a specific column
a[:, 2]

array([ 3, 10])

In [19]:
# Getting more fancy [startindex:endindex:stepsize]
a[0,1:6:2]

array([2, 4, 6])

In [20]:
# change element
a[1,5] = 20
a

array([[ 1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 20, 14]])

In [21]:
a[:, 2] = 5
a

array([[ 1,  2,  5,  4,  5,  6,  7],
       [ 8,  9,  5, 11, 12, 20, 14]])

In [22]:
a[0, :] = [1]
a

array([[ 1,  1,  1,  1,  1,  1,  1],
       [ 8,  9,  5, 11, 12, 20, 14]])

In [23]:
# 3d
d = np.array([[[1,2], [3,4]],[[5,6], [7,8]]])
d

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [24]:
# Get specific element
d[0,1,1]

4

In [25]:
# replace 
d[:, 1, :] = [[9,9], [8,8]]
d

array([[[1, 2],
        [9, 9]],

       [[5, 6],
        [8, 8]]])

# Intialiazing Different Types of Arrays

In [26]:
# All 0's matrix
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [27]:
# All 1's matrix
np.ones((2,3), dtype=np.int32)

array([[1, 1, 1],
       [1, 1, 1]], dtype=int32)

In [28]:
# Any other number
np.full((2,2), 99)

array([[99, 99],
       [99, 99]])

In [29]:
# Any other number (full_like)
np.full_like(a, 4)

array([[4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4]])

In [30]:
# Random decimal numbers
np.random.rand(4,2)

array([[0.58674223, 0.16391079],
       [0.64570026, 0.20157298],
       [0.2957441 , 0.33077696],
       [0.30666201, 0.72830829]])

In [31]:
np.random.random_sample(a.shape)

array([[0.97972581, 0.08949615, 0.89238151, 0.0791713 , 0.76693798,
        0.24810644, 0.30621015],
       [0.55584544, 0.97067613, 0.60697453, 0.88517426, 0.50822255,
        0.471477  , 0.42872544]])

In [32]:
# Random integer value
np.random.randint(0,2, size=(3,3))

array([[1, 1, 0],
       [0, 1, 0],
       [0, 1, 0]])

In [33]:
# identity matrix
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [34]:
# Repeat
arr = np.array([1,2,3])
r1 = np.repeat(arr, 3)
r1

array([1, 1, 1, 2, 2, 2, 3, 3, 3])

## Basic Project

In [35]:
output = np.ones((5,5))
output

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [36]:
z = np.zeros((3,3))
z

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [37]:
z[1,1] = 9
z

array([[0., 0., 0.],
       [0., 9., 0.],
       [0., 0., 0.]])

In [38]:
output[1:4,1:4] = z
output

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 9., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

## Be careful when copying arrays

In [39]:
a = np.array([1,2,3])
a

array([1, 2, 3])

In [40]:
# Directly equalizing b to a
b = a
b

array([1, 2, 3])

In [41]:
# when changin the value of b, it changes the value of a
b[0] = 100
print(b)
print(a)

[100   2   3]
[100   2   3]


In [42]:
# using copy function, doesnt change the value of a.
a = np.array([1,2,3])
b = a.copy()
b[0] = 100
print(a)

[1 2 3]


 # Mathematics

In [43]:
a = np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [44]:
a + 2

array([3, 4, 5, 6])

In [45]:
a - 2

array([-1,  0,  1,  2])

In [46]:
a * 2

array([2, 4, 6, 8])

In [47]:
a / 2

array([0.5, 1. , 1.5, 2. ])

In [48]:
a += 2
a

array([3, 4, 5, 6])

In [49]:
b = np.array([1,0,1,0])
a + b

array([4, 4, 6, 6])

In [50]:
a**2

array([ 9, 16, 25, 36])

In [51]:
# take the sin
np.sin(a)

array([ 0.14112001, -0.7568025 , -0.95892427, -0.2794155 ])

In [52]:
np.cos(a)

array([-0.9899925 , -0.65364362,  0.28366219,  0.96017029])

# Linear Algebra

In [53]:
a = np.ones((2,3))
a

array([[1., 1., 1.],
       [1., 1., 1.]])

In [54]:
b = np.full((3,2), 2)
b

array([[2, 2],
       [2, 2],
       [2, 2]])

In [55]:
# matrix multiplication
np.matmul(a,b)

array([[6., 6.],
       [6., 6.]])

In [56]:
c = np.identity(3)
c

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [57]:
# Find determinant in linear algebra
np.linalg.det(c)

1.0

# Statistics

In [58]:
stats = np.array([[1,2,3], [4,5,6]])
stats

array([[1, 2, 3],
       [4, 5, 6]])

In [59]:
np.min(stats)

1

In [60]:
np.max(stats)

6

In [61]:
# row basis min
np.min(stats, axis=1)

array([1, 4])

In [63]:
# sum
np.sum(stats)

21

# Reorganizing arrays

In [66]:
before = np.array([[1,2,3,4], [5,6,7,8]])
print(before.shape)

(2, 4)


In [67]:
after = before.reshape((8,1))
after

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8]])

In [68]:
after = before.reshape((2,2,2))
after

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [69]:
# Vertocally stacking vectors
v1 = np.array([1,2,3,4])
v2 = np.array([5,6,7,8])

np.vstack([v1, v2])

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [70]:
np.vstack([v1, v2, v2])

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [5, 6, 7, 8]])

In [73]:
# Horizontal Stack
h1 = np.ones((2,4))
h2 = np.zeros((2,2))

np.hstack((h1,h2))

array([[1., 1., 1., 1., 0., 0.],
       [1., 1., 1., 1., 0., 0.]])

# Miscellaneous

### Load Data From File

In [76]:
filedata = np.genfromtxt('data.txt', delimiter=',', dtype=np.int32)
filedata

array([[  1,  13,  21,  11, 196,  75,   4,   3,  34,   6,   7,   8,   0,
          1,   2,   3,   4,   5],
       [  3,  42,  12,  33, 766,  75,   4,  55,   6,   4,   3,   4,   5,
          6,   7,   0,  11,  12],
       [  1,  22,  33,  11, 999,  11,   2,   1,  78,   0,   1,   2,   9,
          8,   7,   1,  76,  -1]], dtype=int32)

### Boolean Maskign and Advanced Indexing

In [78]:
filedata[filedata > 50]

array([196,  75, 766,  75,  55, 999,  78,  76], dtype=int32)

In [79]:
# You can index with a list in Numpy
a = np.array([1,2,3,4,5,6,7,8,9])
a[[1,2,8]]

array([2, 3, 9])

In [80]:
np.any(filedata > 50, axis=0)

array([False, False, False, False,  True,  True, False,  True,  True,
       False, False, False, False, False, False, False,  True, False])